#pragma once

BEGIN(Engine)

enum COORDINATE { COORDINATE_2D, COORDINATE_3D, COORDINATE_LAST };

enum IMPORT_MODE {NONE_IMPORT = 0x00, IMPORT_MESH_PICKING = 0x02, IMPORT_IMGUI = 0x04, IMPORT_MODE_LAST};

#define IMPORT_ALL (IMPORT_MODE)(IMPORT_MESH_PICKING | IMPORT_IMGUI)
#define IS_IMPORT_IMGUI (IMPORT_MODE::IMPORT_IMGUI & m_pGameInstance->Get_ImportMode())
#define IS_IMPORT_MESHPICKING (IMPORT_MODE::IMPORT_MESH_PICKING & m_pGameInstance->Get_ImportMode())

enum PBR_TONEMAPPING { TONE_LINEAR, TONE_FILMIC, TONE_UNCHARTED2, TONE_LUMAREINHARD, TONE_LAST };

enum class LIGHT_TYPE { POINT, DIRECTOINAL, SPOT, LAST };

enum RATIO_TYPE { EASE_IN, EASE_OUT, LERP, EASE_IN_OUT, RATIO_TYPE_LAST };

enum IBLTEXTURE { IBL_TEST, IBL_CHAPTER2_BRIGHT, IBL_CHAPTER2_NIGHT, IBL_CHAPTER4, IBL_CHAPTER6, IBL_CHAPTER6_2, IBL_LAST };
enum class NORMAL_DIRECTION
{
	NONEWRITE_NORMAL = -1,
	POSITIVE_X = 0,
	NEGATIVE_X = 1,
	POSITIVE_Y = 2,
	NEGATIVE_Y = 3,
	POSITIVE_Z = 4,
	NEGATIVE_Z = 5,

	LAST
};
enum class UI_DEPTHTYPE
{
	FIXED,
	UNFIXED,

	LAST,
};

enum class PASS_VTXCUBE
{
	DEFAULT,
	HDRI_ENV,

	LAST
};

enum class PASS_VTXPOSTEX
{
	DEFAULT,
	ALPHA,
	ALPHA_ZWRITENONE,
	COLOR_ALPHA,
	SPRITE2D,
	UI_POINTSAMPLE,
	UI_ALPHA,
	MAPOBJECT_MIXCOLOR,
	DIALOGUE_BG_COLOR,
	RATIO_BOTTOM_UP,
	BACKGROUND,
	SPRITE2D_UVCUT,
	LAST
};

enum class PASS_VTXMESH
{
	DEFAULT,
	AFTERPOSTPROCESSING,
	ALPHABLEND,
	NONECULL,
	COLOR,
	MIX_COLOR,
	TEST_PROJECTILE,
	WORLDPOSMAP_BOOK,
	PLAYERDEPTH,
	RENDERTARGET_MAPP,
	RENDERTARGET_MAPP_AFTERPOSTPROCESSING,
	SHADOWMAP,
	EMISSIVE_COLOR,
	FRESNEL,
	BACKGROUND,
	TRAIL,
	NOISEFRESNEL,
	NOISEFRESNEL_BILLBOARD,

	LAST
};

enum class PASS_VTXANIMMESH
{
	DEFAULT,
	AFTERPOSTPROCESSING,
	ALPHABLEND,
	NONECULL,
	RENDERTARGET_MAPP,
	RENDERTARGET_MAPP_AFTERPOSTPROCESSING,
	WORLDPOSMAP_BOOK,
	FRESNELS,
	PLAYERDEPTH,
	SHADOWMAP,
	TRAIL,
	TEXTUREBLENDING,
	LAST
};

enum class PASS_DEFERRED
{
	DEBUG,
	LIGHTING,
	COMBINE,
	AFTER_EFFECT,
	AFTER_PARTICLE,
	BLURDOWN,
	BLURDOWN2,
	BLUR,
	// deferrer pass 수정하면서 이넘 맞춰야함.
	PBR_LIGHT_POINT,
	PBR_LIGHT_DIRECTIONAL,
	PBR_LIGHT_SPOT,
	PBR_BLUR_DOWN,
	PBR_BLUR_UP,
	PBR_BLUR_FINAL,
	FINAL,
	LAST
};

enum class PASS_VTXPOINTINSTANCE
{
	LOOP,
	ONCE,

	LAST
};
enum RENDERING_FLAG
{
	RENDERING_FLAG_DEFAULT = 0x00,
	RENDERING_FLAG_NORMALMAP = 0x01,

};

/* Physx를 위한 enum 들 */
enum class SHAPE_TYPE { BOX, SPHERE, CAPSULE, COOKING, LAST };
enum class ACTOR_TYPE { STATIC, KINEMATIC, DYNAMIC, LAST }; /* 더 다양한 타입이 있으나 일단 우린 이정도 선에서 사용할 것이기때문.*/
enum class ACTOR_MATERIAL { DEFAULT, SLIPPERY, BOUNCY, STICKY,NOFRICTION,CHARACTER_CAPSULE,NORESTITUTION,DOMINO,CHARACTER_FOOT, CASTLE_GATE, CUSTOM };
END
