#pragma once

BEGIN(Engine)

enum COORDINATE { COORDINATE_2D, COORDINATE_3D, COORDINATE_LAST };

enum PBR_TONEMAPPING { TONE_LINEAR, TONE_FILMIC, TONE_UNCHARTED2, TONE_LUMAREINHARD, TONE_LAST };

enum class LIGHT_TYPE { POINT, DIRECTOINAL, LAST };

enum class UI_DEPTHTYPE
{
	FIXED,
	UNFIXED,

	LAST,
};

enum class PASS_VTXCUBE
{
	DEFAULT,
	HDRI_ENV,

	LAST
};

enum class PASS_VTXPOSTEX
{
	DEFAULT,
	ALPHA,
	ALPHA_ZWRITENONE,
	COLOR_ALPHA,
	SPRITE2D,
	UI_POINTSAMPLE,
	UI_ALPHA,
	MAPOBJECT_MIXCOLOR,
	DIALOGUE_BG_COLOR,
	LAST
};

enum class PASS_VTXMESH
{
	DEFAULT,
	NONECULL,
	LIGHTDEPTH,
	COLOR,
	MIX_COLOR,
	TEST_PROJECTILE,
	WORLDPOSMAP_BOOK,

	LAST
};

enum class PASS_VTXANIMMESH
{
	DEFAULT,
	ALPHA,
	NONECULL,
	LIGHTDEPTH,
	RENDERTARGET_MAPP,
	WORLDPOSMAP_BOOK,
	LAST
};

enum class PASS_DEFERRED
{
	DEBUG,
	LIGHTING,
	COMBINE,
	AFTER_EFFECT,
	AFTER_PARTICLE,
	BLURDOWN,
	BLURDOWN2,
	BLUR,
	// deferrer pass 수정하면서 이넘 맞춰야함.
	PBR_LIGHT_POINT,
	PBR_LIGHT_DIRECTIONAL,
	PBR_BLUR_DOWN,
	PBR_BLUR_UP,
	LAST
};

enum class PASS_VTXPOINTINSTANCE
{
	LOOP,
	ONCE,

	LAST
};
enum RENDERING_FLAG
{
	RENDERING_FLAG_DEFAULT = 0x00,
	RENDERING_FLAG_NORMALMAP = 0x01,

};

/* Physx를 위한 enum 들 */
enum class SHAPE_TYPE { BOX, SPHERE, CAPSULE, COOKING, LAST };
enum class ACTOR_TYPE { STATIC, KINEMATIC, DYNAMIC, LAST }; /* 더 다양한 타입이 있으나 일단 우린 이정도 선에서 사용할 것이기때문.*/
enum class ACTOR_MATERIAL { DEFAULT, SLIPPERY, BOUNCY, STICKY,NOFRICTION,CHARACTER_CAPSULE,NORESTITUTION, CUSTOM };
END
