#pragma once
#include "Engine_Defines.h"
namespace Client
{
	enum RENDERGROUP
	{
		RG_2D = 1000,
		RG_3D = 2000,


		RG_WORLDPOSMAP = 9000,
		RG_LAST,
	};

	enum PRIORITY_3D
	{
		PR3D_PRIORITY =			10,
		PR3D_SHADOW =			20,
		PR3D_GEOMETRY =			30,
		PR3D_DIRECTLIGHTS =		40,
		PR3D_LIGHTNG =			50, // >>> 리졸빙
		PR3D_POSTPROCESSING =		52, // PostProcessing
		PR3D_SSAO =				54, // PostProcessing
		PR3D_COMBINE =			60, // ToneMapping
		PR3D_BLEND =			70,
		PR3D_EFFECT = 80,
		PR3D_PARTICLE = 90,
		PR3D_AFTERPARTICLE = 100,
		PR3D_BLURDOWN = 110,
		PR3D_BLUR = 120,
		PR3D_AFTEREFFECT = 130,
		PR3D_UI = 140,

		PR3D_LAST = 999
	};

	
	enum PRIORITY_2D
	{
		// 전처리 그룹
		PR2D_PRIORITY =			0,
		PR2D_SECTION_START =	10,
		// 10 ~ 970 
		//-> 섹션 유동생성 발급
		
		PR2D_SECTION_END =		970,
		PR2D_UI =				980,
		// 후처리 그룹
		PR2D_AFTER =			990,
		PR2D_LAST =				999
	};

	enum PRIORITY_WORLDPOSMAP
	{
		PRWORLD_MAINBOOK =		0,
		PRWORLD_SKETCH_START =	100,

		PRWORLD_SKETCH_END =	300,
		PRWORLD_LAST =			999
	};

	enum LEVEL_ID 
	{
		LEVEL_LOADING,
		LEVEL_STATIC,
		LEVEL_LOGO,
		LEVEL_CHAPTER_2,
		LEVEL_CHAPTER_4,
		LEVEL_CHAPTER_TEST,

		LEVEL_END
	};


	enum SECTION_PLAYMAP_2D_RENDERGROUP
	{
		SECTION_2D_PLAYMAP_BACKGROUND,
		SECTION_2D_PLAYMAP_PORTAL,
		SECTION_2D_PLAYMAP_OBJECT,
		SECTION_2D_PLAYMAP_TRIGGER,
		SECTION_2D_PLAYMAP_UI,
		SECTION_2D_PLAYMAP_RENDERGROUP_LAST,
	};

	// 비트연산자를 통해 SimulationFilter를 설정해야해서 enum으로 하겠음. enum class는 비트연산자 쓰려면 형변환많이하고 번거로워서.
	enum OBJECT_GROUP // 아래 GROUP은 예시임. 편한대로 사용하시면 됨.
	{
		NONE =						0x00,
		PLAYER =					0x01,
		MONSTER =					0x02,//1
		MAPOBJECT =					0x04, //2
		INTERACTION_OBEJCT =		0x08,
		PLAYER_PROJECTILE =			0x10,//4
		MONSTER_PROJECTILE =		0x20,//5
		TRIGGER_OBJECT =		    0x40,
		RAY_OBJECT =				0x80,
		PLAYER_TRIGGER =			0x100,
		BLOCKER = 					0x200,		
		PORTAL = 					0x400,		
								 // 0x800 

		LAST =					0x40000000 // == 2의 32승 (32개 이상의 그룹은 X) -> enum은 기본 int므로, 오버플로우 발생 여지 있음. 최대값을 30승으로 제한. 0215 박예슬
	};


	enum class EVENT_TYPE 
	{
		CREATE_OBJECT,
		DELETE_OBJECT,
		LEVEL_CHANGE,
		SET_ACTIVE,
		SETUP_SIMULATION_FILTER,
		CHANGE_MONSTERSTATE,
		CHANGE_BOSSSTATE,
		CHANGE_COORDINATE,
		SET_KINEMATIC,
		TRIGGER_ENTER_EVENT,
		TRIGGER_STAY_EVENT,
		TRIGGER_EXIT_EVENT,
		TRIGGER_FREEZE_ENTER_EVENT,
		TRIGGER_LOOKAT_ENTER_EVENT,
		TRIGGER_EXIT_BYCOLLISION_EVENT,
		BOOK_MAIN_SECTION_CHANGE_ACTION_START,
		BOOK_MAIN_SECTION_CHANGE_ACTION_END,
		BOOK_MAIN_CHANGE,
		SET_SCENEQUERYFLAG,
		HIT,
		GET_BULB,
		ADDIMPULSE,
		SNEAK_BEETLECAUGHT,
		
		LAST,
	};

	enum class TRIGGER_TYPE
	{
		EVENT_TRIGGER,
		ARM_TRIGGER,
		CUTSCENE_TRIGGER,
		FREEZE_X_TRIGGER,
		FREEZE_Z_TRIGGER,
		TELEPORT_TRIGGER,
		SECTION_CHANGE_TRIGGER,
		DEFAULT_TRIGGER,
		ENABLE_LOOKAT_TRIGGER,

		LAST
	};

	enum class MONSTER_STATE
	{
		IDLE,
		PATROL,
		ALERT,
		STANDBY,
		CHASE,
		ATTACK,
		HIT,
		DEAD,
		SNEAK_IDLE,
		SNEAK_PATROL,
		SNEAK_BACK,
		SNEAK_AWARE,
		SNEAK_INVESTIGATE,
		SNEAK_ALERT,
		SNEAK_CHASE,
		SNEAK_ATTACK,

		LAST,
	};

	enum class BOSS_STATE
	{
		SCENE,
		IDLE,
		ATTACK,
		ENERGYBALL,
		HOMINGBALL,
		YELLOWBALL,
		PURPLEBALL,

		LAST,
	};

	enum class F_DIRECTION
	{
		LEFT,
		RIGHT,
		UP,
		DOWN,
		F_DIR_LAST
	};
	enum class E_DIRECTION
	{
		LEFT,
		RIGHT,
		UP,
		DOWN,
		LEFT_UP,
		RIGHT_UP,
		RIGHT_DOWN,
		LEFT_DOWN,
		E_DIR_LAST
	};
	enum class T_DIRECTION
	{
		LEFT,
		RIGHT,
		NONE,
		T_DIR_LAST
	};

	enum class WAYPOINTINDEX
	{
		CHAPTER2_1,
		CHAPTER2_2,
		CHAPTER2_2_2,
		CHAPTER2_3,
		LAST
	};

	enum class SHAPE_USE
	{
		SHAPE_BODY = 0,
		SHAPE_FOOT = 1,
		SHAPE_TRIGER = 2
	};
}
