#pragma once
#include "Character.h"

BEGIN(Client)
class CStateMachine;
class CPlayer final : public CCharacter
{
public:
	enum PLAYER_PART
	{
		PLAYER_PART_SWORD= 1,
		PLAYER_PART_GLOVE,
		PLAYER_PART_STAMP,
		PLAYER_PART_LAST
	};
	enum STATE
	{
		IDLE,
		RUN,
		JUMP,
		ATTACK,
		STATE_LAST
	};
	enum class ANIM_STATE_2D
	{
		C08_0708_FX_GEARUP
		,JOT_GATEPASS
		,JOT_HANDEVICT
		,JOT_HANDEVICT_HAND
		,JOT_HANDEVICT_SMUSHLOOP
		,JOT_HANDEVICT_SWORD
		,JOT_HANDEVICT_SWORD_INGROUND
		,LATCHSWORDSTUCK_FLIPBOOK
		,LATCHSWORD_
		,PLAYER_C06_END
		,PLAYER_C06_IDLE01 = 10
		,PLAYER_C06_IDLE01TRANSITION
		,PLAYER_C06_IDLE01_INTO
		,PLAYER_C06_IDLE02
		,PLAYER_C06_IDLE03
		,PLAYER_C06_LOOKUP
		,PLAYER_C08V02_END
		,PLAYER_C08V02_IDLE01
		,PLAYER_C08V02_IDLE02
		,PLAYER_C08V02_LOOKUPLEFT
		,PLAYER_C08V02_LOOKUPRIGHT
		,PLAYER_CLIFFCRUMBLE
		,PLAYER_CYBERJOTLITE_RUN_IDLE_TEMP
		,PLAYER_CYBERJOTLITE_RUN_RIGHT
		,PLAYER_CYBERJOTLITE_TRANSFORM
		,PLAYER_GIVEPOP
		,PLAYER_GIVEWAND
		,PLAYER_SLEEPING_LOOP
		,PLAYER_SLEEPING_WAKEUP
		,PLAYER_SLIPPINGV02_NOSWORD_DOWN
		,PLAYER_SLIPPINGV02_NOSWORD_RIGHT
		,PLAYER_SLIPPINGV02_NOSWORD_UP
		,PLAYER_SLIPPINGV02_SWORD_DOWN
		,PLAYER_SLIPPINGV02_SWORD_RIGHT
		,PLAYER_SLIPPINGV02_SWORD_UP
		,PLAYER_TUMBADANCEV03
		,PLAYER_MOJAM_MOJAM
		,PLAYER_MOJAM_MOJAM_C02_0910
		,PLAYER_MOJAM_MOJAM_C10_0910
		,SWORDSPINNING
		,ZIP_IDLE_2
		,ZIP_JUMP_RISE
		,ZIP_JUMP_FALL
		,ZIP_ASCEND
		,ZIP_ATTACK
		,ZIP_DESCEND
		,ZIP_FLOAT
		,ZIP_RUN
		,ZIP_SWORDTHROW_INTO
		,ZIP_SWORDTHROW_LOOP
		,ZIP_SWORDTHROW_OUT
		,JOT_GAMEOVER
		,JOT_GAMEOVER_LOOP
		,JOT_GAMEOVER_NOSWORD
		,JOT_GAMEOVER_NOSWORD_LOOP
		,JOT_LOOKUP_HOLD_RIGHT
		,JOT_LOOKUP_RIGHT
		,JOT_SURPRISE_HOLD_RIGHT
		,JOT_SURPRISE_RIGHT
		,JOT_TOIDLE_RIGHT
		,JUMP_IN_PLAYER_ZIPIN_DOWN
		,JUMP_IN_PLAYER_ZIPIN_RIGHT
		,JUMP_IN_PLAYER_ZIPIN_UP
		,JUMP_OUT_PLAYER_ZIPOUT_DOWN_EDIT
		,JUMP_OUT_PLAYER_ZIPOUT_RIGHT_EDIT
		,JUMP_OUT_PLAYER_ZIPOUT_UP_EDIT
		,PLAYER_FX_FLASH
		,PLAYER_FX_POP
		,PLAYER_ATTACK_DOWN = 68 
		,PLAYER_ATTACK_RIGHT
		,PLAYER_ATTACK_UP
		,PLAYER_ATTACKCOMBO_01_SS
		,PLAYER_ATTACKCOMBO_01_DOWN
		,PLAYER_ATTACKCOMBO_01_RIGHT
		,PLAYER_ATTACKCOMBO_01_UP
		,PLAYER_ATTACKCOMBO_03_SS
		,PLAYER_ATTACKCOMBO_03_DOWN
		,PLAYER_ATTACKCOMBO_03_RIGHT
		,PLAYER_ATTACKCOMBO_03_UP
		,PLAYER_ATTACKV02_SPIN_DOWN_LVL1
		,PLAYER_ATTACKV02_SPIN_DOWN_LVL2
		,PLAYER_ATTACKV02_SPIN_DOWN_LVL3
		,PLAYER_ATTACKV02_SPIN_DOWN_LVL4
		,PLAYER_ATTACKV02_SPIN_INTO_DOWN
		,PLAYER_ATTACKV02_SPIN_INTO_RIGHT
		,PLAYER_ATTACKV02_SPIN_INTO_UP
		,PLAYER_ATTACKV02_SPIN_RIGHT_LVL1
		,PLAYER_ATTACKV02_SPIN_RIGHT_LVL2
		,PLAYER_ATTACKV02_SPIN_RIGHT_LVL3
		,PLAYER_ATTACKV02_SPIN_RIGHT_LVL4
		,PLAYER_ATTACKV02_SPIN_UP_LVL1
		,PLAYER_ATTACKV02_SPIN_UP_LVL2
		,PLAYER_ATTACKV02_SPIN_UP_LVL3
		,PLAYER_ATTACKV02_SPIN_UP_LVL4
		,PLAYER_ATTACKV02_SS
		,PLAYER_BOOKENTER_DOWN
		,PLAYER_BOOKENTER_FALL_DOWN
		,PLAYER_BOOKENTER_FALL_RIGHT
		,PLAYER_BOOKENTER_FALL_UP
		,PLAYER_BOOKENTER_RIGHT
		,PLAYER_BOOKENTER_UP
		,PLAYER_BOOKEXIT_DOWN
		,PLAYER_BOOKEXIT_RIGHT
		,PLAYER_BOOKEXIT_UP
		,PLAYER_C06_CRUSHROOMGET
		,PLAYER_C06_CRUSHROOMGET_IDLE
		,PLAYER_C06_POWERUP_END
		,PLAYER_C06_RAISESWORD
		,PLAYER_C06_RAISESWORD_LOOP
		,PLAYER_C06_SWORDBEAM_LOOP
		,PLAYER_C06_SWORDBEAM_OUT
		,PLAYER_CANNON_CURL_CANCEL
		,PLAYER_CANNON_CURL_INTO
		,PLAYER_CANNON_CURL_SPIN
		,PLAYER_CANNONCHARGE_DOWN
		,PLAYER_CANNONCHARGE_RIGHT
		,PLAYER_CANNONCHARGE_UP
		,PLAYER_CARRY_IDLE_DOWN
		,PLAYER_CARRY_IDLE_RIGHT
		,PLAYER_CARRY_IDLE_RIGHT_SS
		,PLAYER_CARRY_IDLE_UP
		,PLAYER_CATCH_GLITCHBIRD
		,PLAYER_CATCH_GLITCHBIRD_OUTLINE
		,PLAYER_CYBERJOTLITE_BOOKEXIT_DOWN
		,PLAYER_DEATH_DOWN
		,PLAYER_DODGEROLL_DOWN_NOSWORD
		,PLAYER_DODGEROLL_DOWN_SINGLEROLLONLY
		,PLAYER_DODGEROLL_RIGHT_NOSWORD
		,PLAYER_DODGEROLL_RIGHT_SINGLEROLLONLY
		,PLAYER_DODGEROLL_UP_NOSWORD
		,PLAYER_DODGEROLL_UP_SINGLEROLLONLY
		,PLAYER_DROP_OBJECT_DOWN
		,PLAYER_DROP_OBJECT_RIGHT
		,PLAYER_DROP_OBJECT_SS
		,PLAYER_DROP_OBJECT_UP
		,PLAYER_ELECTROCUTE
		,PLAYER_HAPPY
		,PLAYER_IDLE_DOWN
		,PLAYER_IDLE_RIGHT
		,PLAYER_IDLE_SWORD_DOWN
		,PLAYER_IDLE_SWORD_RIGHT
		,PLAYER_IDLE_SWORD_UP
		,PLAYER_IDLE_UP
		,PLAYER_ITEM_RETRIEVE
		,PLAYER_ITEM_RETRIEVE_V02
		,PLAYER_JUMP_FALL_DOWN
		,PLAYER_JUMP_FALL_OBJECT_DOWN
		,PLAYER_JUMP_FALL_OBJECT_RIGHT
		,PLAYER_JUMP_FALL_OBJECT_UP
		,PLAYER_JUMP_FALL_RIGHT
		,PLAYER_JUMP_FALL_SWORD_DOWN
		,PLAYER_JUMP_FALL_SWORD_RIGHT
		,PLAYER_JUMP_FALL_SWORD_UP
		,PLAYER_JUMP_FALL_UP
		,PLAYER_JUMP_RISE_DOWN
		,PLAYER_JUMP_RISE_OBJECT_DOWN
		,PLAYER_JUMP_RISE_OBJECT_RIGHT
		,PLAYER_JUMP_RISE_OBJECT_UP
		,PLAYER_JUMP_RISE_RIGHT
		,PLAYER_JUMP_RISE_SWORD_DOWN
		,PLAYER_JUMP_RISE_SWORD_RIGHT
		,PLAYER_JUMP_RISE_SWORD_UP
		,PLAYER_JUMP_RISE_UP
		,PLAYER_JUMP_RISE_UP_
		,PLAYER_JUMPCARRY_RISE_DOWN
		,PLAYER_JUMPCARRY_RISE_UP
		,PLAYER_JUMPINGATTACK_FX
		,PLAYER_JUMPINGATTACK_FALL_DOWN
		,PLAYER_JUMPINGATTACK_FALL_RIGHT
		,PLAYER_JUMPINGATTACK_FALL_UP
		,PLAYER_JUMPINGATTACK_OUT_DOWN
		,PLAYER_JUMPINGATTACK_OUT_RIGHT
		,PLAYER_JUMPINGATTACK_OUT_UP
		,PLAYER_JUMPINGATTACK_RISE_DOWN
		,PLAYER_JUMPINGATTACK_RISE_RIGHT
		,PLAYER_JUMPINGATTACK_RISE_UP
		,PLAYER_KNOCKEDBACK_FLOOR
		,PLAYER_KNOCKEDBACK_INTO
		,PLAYER_KNOCKEDBACK_LOOP
		,PLAYER_KNOCKEDBACK_OUT
		,PLAYER_MOJAM_INTO
		,PLAYER_PICKUP_IDLE_DOWN
		,PLAYER_PICKUP_IDLE_RIGHT
		,PLAYER_PICKUP_IDLE_UP
		,PLAYER_PICKUP_OBJECT_DOWN
		,PLAYER_PICKUP_OBJECT_RIGHT
		,PLAYER_PICKUP_OBJECT_SS
		,PLAYER_PICKUP_OBJECT_UP
		,PLAYER_PULL_LOOP
		,PLAYER_PULL_OBJECT_DOWN
		,PLAYER_PULL_OBJECT_RIGHT
		,PLAYER_PULL_OBJECT_SS
		,PLAYER_PULL_OBJECT_UP
		,PLAYER_PUSH_OBJECT_DOWN
		,PLAYER_PUSH_OBJECT_RIGHT
		,PLAYER_PUSH_OBJECT_SS
		,PLAYER_PUSH_OBJECT_UP
		,PLAYER_ROLL_INTO
		,PLAYER_ROLL_LOOP
		,PLAYER_ROLL_OUT
		,PLAYER_RUN_DOWN = 200
		,PLAYER_RUN_OBJECT_DOWN
		,PLAYER_RUN_OBJECT_RIGHT
		,PLAYER_RUN_OBJECT_UP
		,PLAYER_RUN_RIGHT
		,PLAYER_RUN_SWORD_DOWN
		,PLAYER_RUN_SWORD_RIGHT
		,PLAYER_RUN_SWORD_UP
		,PLAYER_RUN_UP
		,PLAYER_SWORD_RETRIEVE
		,PLAYER_SWORDTHROW_AIMLOOP_DOWN
		,PLAYER_SWORDTHROW_AIMLOOP_RIGHT
		,PLAYER_SWORDTHROW_AIMLOOP_UP
		,PLAYER_SWORDTHROW_INTO_DOWN
		,PLAYER_SWORDTHROW_INTO_RIGHT
		,PLAYER_SWORDTHROW_INTO_UP
		,PLAYER_SWORDTHROW_OUT_DOWN
		,PLAYER_SWORDTHROW_OUT_RIGHT
		,PLAYER_SWORDTHROW_OUT_UP
		,PLAYER_THROW_OBJECT_DOWN
		,PLAYER_THROW_OBJECT_RIGHT
		,PLAYER_THROW_OBJECT_UP
		,PLAYER_TRAPPED
		,PLAYER_ZIPLINE
		,ZIP_DIE
	};
	enum class ANIM_STATE_3D
	{
		LATCH_ANIM_BOOK_JUMP_FALL_RIGHT
		,LATCH_ANIM_BOOK_JUMP_LAND_RIGHT
		,LATCH_ANIM_IDLE_01
		,LATCH_ANIM_JUMP_LAND_02
		,LATCH_ANIM_JUMP_UP_02
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_BEHIND_LATCH
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_BEHIND_LOOP_LATCH
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_FRONT_LATCH
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_FRONT_LOOP_LATCH
		,LATCH_TURN_LEFT
		,LATCH_TURN_MID
		,LATCH_TURN_RIGHT
		,LATCH_ANIM_ATTACK_02_GT
		,LATCH_ANIM_ATTACK_03_GT
		,LATCH_ANIM_BOOK_JUMP_FALL_BACK_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_FALL_FRONT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_FALL_LEFT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_BACK_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_FRONT_GT
		,LATCH_ANIM_BOOK_JUMP_INTO_FRONT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_LEFT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_RIGHT_GT
		,LATCH_ANIM_BOOK_JUMP_INTO_RIGHT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_LAND_BACK_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_LAND_FRONT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_LAND_LEFT_NEWRIG
		,LATCH_ANIM_BOOKOUT_01_GT
		,LATCH_ANIM_CALL_GT
		,LATCH_ANIM_CALL_NEWRIG
		,LATCH_ANIM_CANON_FLY_GT
		,LATCH_ANIM_CANON_FLY_LAND_GT
		,LATCH_ANIM_CAUGHT_GT
		,LATCH_ANIM_CLAMBER_01_EDIT_NEWRIG
		,LATCH_ANIM_CLAMBER_01_GT
		,LATCH_ANIM_DIE_GT
		,LATCH_ANIM_DIE_NEWRIG
		,LATCH_ANIM_DODGE_GT
		,LATCH_ANIM_DRAGGED_BWD_GT
		,LATCH_ANIM_DRAGGED_FWD_GT_ANIM
		,LATCH_ANIM_IDLE_01_GT
		,LATCH_ANIM_IDLE_NERVOUS_01_GT
		,LATCH_ANIM_IDLE_NERVOUS_01_NEWRIG
		,LATCH_ANIM_IDLE_NERVOUS_TURN_01_GT
		,LATCH_ANIM_IDLE_NERVOUS_TURN_01_NEWRIG
		,LATCH_ANIM_ITEM_GET_GT
		,LATCH_ANIM_ITEM_GET_NEWRIG
		,LATCH_ANIM_JUMP_DOWN_01_NEWRIG
		,LATCH_ANIM_JUMP_DOWN_02_GT
		,LATCH_ANIM_JUMP_DOWN_02_NEWRIG
		,LATCH_ANIM_JUMP_LAND_02_GT
		,LATCH_ANIM_JUMP_START_SHORT_GT
		,LATCH_ANIM_JUMP_START_SHORT_NEWRIG
		,LATCH_ANIM_JUMP_UP_02_GT
		,LATCH_ANIM_JUMPATTACK_RISE_GT
		,LATCH_ANIM_LUNCHBOX_BACKFLIP_GT
		,LATCH_ANIM_LUNCHBOX_POSE_01_LOOP_GT
		,LATCH_ANIM_LUNCHBOX_POSE_02_LOOP_GT
		,LATCH_ANIM_PULL_GT
		,LATCH_ANIM_PULL_LEFT_GT
		,LATCH_ANIM_PULL_RIGHT_GT
		,LATCH_ANIM_PUSH_GT
		,LATCH_ANIM_PUTDOWN_GT
		,LATCH_ANIM_PUTDOWN_NEWRIG
		,LATCH_ANIM_REMOTE_HOLD
		,LATCH_ANIM_REMOTE_PUSH_GT
		,LATCH_ANIM_RUN_01_GT
		,LATCH_ANIM_RUN_SWORD_01_GT
		,LATCH_ANIM_SPIN_ATTACK_INTO_GT
		,LATCH_ANIM_SPIN_ATTACK_OUT_GT
		,LATCH_ANIM_SPIN_ATTACK_SPIN_LOOP_GT
		,LATCH_ANIM_SPRINT_01_NEWRIG
		,LATCH_ANIM_STAMP_ATTACK_EDIT_NEWRIG
		,LATCH_ANIM_STAMP_ATTACK_GT
		,LATCH_ANIM_STAMP_ERASE_GT
		,LATCH_ANIM_STAMP_HOLD_GT
		,LATCH_ANIM_STAMP_HOLD_NEWRIG
		,LATCH_ANIM_STAMP_PULLOUT_SHORT_GT
		,LATCH_ANIM_STAMP_PULLOUT_SHORT_GT_EDIT
		,LATCH_ANIM_STAMP_PULLOUT_SHORT_NEWRIG
		,LATCH_ANIM_STEALTH_RUN_GT
		,LATCH_ANIM_SWORDTHROW_AIM_GT
		,LATCH_ANIM_SWORDTHROW_AIM_NEWRIG
		,LATCH_ANIM_SWORDTHROW_INTO_GT
		,LATCH_ANIM_SWORDTHROW_INTO_NEWRIG
		,LATCH_ANIM_SWORDTHROW_THROW_GT
		,LATCH_ANIM_SWORDTHROW_THROW_NEWRIG
		,LATCH_ANIM_TORCH_STRAFE_BACK_01_GT
		,LATCH_ANIM_TORCH_STRAFE_FWD_01_GT
		,LATCH_ANIM_TORCH_STRAFE_LEFT_01_GT
		,LATCH_ANIM_TORCH_STRAFE_RIGHT_01_GT
		,LATCH_ANIM_TRAILER_OUTBOOK_01_ANIM
		,LATCH_CINE_D09_LB_INTRO_SH_01
		,LATCH_CINE_D09_LB_INTRO_SH_02
		,LATCH_CINE_D09_LB_INTRO_SH_03
		,LATCH_CINE_GAUNTLET_EVENT_SHOT_01_GT
		,LATCH_PICKUP_GT
		,LATCH_PICKUP_IDLE_GT
		,LATCH_PICKUP_IDLE_NEWRIG
		,LATCH_PICKUP_NEWRIG
		,LATCH_STEALTH_IDLE_GT
		,LATCH_THROW_NEWRIG
		,LATCH_ANIM_ATTACK_01_BLOCKED_GT_EDIT
		,LATCH_ANIM_ATTACK_01_GT_EDIT
		,LATCH_ANIM_JUMPATTACK_FALL
		,LATCH_ANIM_JUMPATTACK_LAND_GT_EDIT
		,LATCH_ANIM_JUMPATTACK_RISE
		,LATCH_ANIM_LAST
	};
private:
	CPlayer(ID3D11Device* _pDevice, ID3D11DeviceContext* _pContext);
	CPlayer(const CPlayer& _Prototype);
	virtual ~CPlayer() = default;

public:
	virtual HRESULT			Initialize_Prototype() override;
	virtual HRESULT			Initialize(void* _pArg) override;
	virtual void			Priority_Update(_float _fTimeDelta) override;
	virtual void			Update(_float _fTimeDelta) override;
	virtual void			Late_Update(_float _fTimeDelta) override;
	virtual HRESULT			Render() override;

	void									On_AnimEnd(COORDINATE _eCoord, _uint iAnimIdx);
	virtual void                     On_CoordinateChange() override;
	virtual HRESULT				Change_Coordinate(COORDINATE _eCoordinate, const _float3& _vPosition) override;
	void Move(_vector _vDir,_float _fTimeDelta);
	void Attack(_uint _iCombo);
	//Get
	F_DIRECTION Get_2DDirection() { return m_e2DDirection; }
	//Set
	void Switch_Animation(_uint _iAnimIndex);
	void Set_State(STATE _eState);
	void Set_2DDirection(F_DIRECTION _eFDir);
	void Equip_Part(PLAYER_PART _ePartId);
	void UnEquip_Part(PLAYER_PART _ePartId);
private:
	void					Key_Input(_float _fTimeDelta);

private:
	HRESULT					Ready_Components();
	HRESULT					Ready_PartObjects();

private:
	CStateMachine* m_pStateMachine = nullptr;
	F_DIRECTION m_e2DDirection = F_DIRECTION::F_DIR_LAST;
	
public:
	static CPlayer*		Create(ID3D11Device* _pDevice, ID3D11DeviceContext* _pContext);
	virtual CGameObject*	Clone(void* _pArg) override;
	virtual void			Free() override;

};
END
