#pragma once
#include "ContainerObject.h"

BEGIN(Client)
class CStateMachine;
class CPlayer final : public CContainerObject
{
public:
	enum STATE
	{
		IDLE,
		RUN,
		JUMP,
		ATTACK,
		STATE_LAST
	};
	enum ANIM_STATE_2D
	{

	};
	enum ANIM_STATE_3D
	{
		LATCH_ANIM_BOOK_JUMP_FALL_RIGHT
		,LATCH_ANIM_BOOK_JUMP_LAND_RIGHT
		,LATCH_ANIM_IDLE_01
		,LATCH_ANIM_JUMP_LAND_02
		,LATCH_ANIM_JUMP_UP_02
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_BEHIND_LATCH
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_BEHIND_LOOP_LATCH
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_FRONT_LATCH
		,LATCH_KNOCKED_DOWN_AND_EATEN_FROM_FRONT_LOOP_LATCH
		,LATCH_TURN_LEFT
		,LATCH_TURN_MID
		,LATCH_TURN_RIGHT
		,LATCH_ANIM_ATTACK_02_GT
		,LATCH_ANIM_ATTACK_03_GT
		,LATCH_ANIM_BOOK_JUMP_FALL_BACK_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_FALL_FRONT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_FALL_LEFT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_BACK_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_FRONT_GT
		,LATCH_ANIM_BOOK_JUMP_INTO_FRONT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_LEFT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_INTO_RIGHT_GT
		,LATCH_ANIM_BOOK_JUMP_INTO_RIGHT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_LAND_BACK_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_LAND_FRONT_NEWRIG
		,LATCH_ANIM_BOOK_JUMP_LAND_LEFT_NEWRIG
		,LATCH_ANIM_BOOKOUT_01_GT
		,LATCH_ANIM_CALL_GT
		,LATCH_ANIM_CALL_NEWRIG
		,LATCH_ANIM_CANON_FLY_GT
		,LATCH_ANIM_CANON_FLY_LAND_GT
		,LATCH_ANIM_CAUGHT_GT
		,LATCH_ANIM_CLAMBER_01_EDIT_NEWRIG
		,LATCH_ANIM_CLAMBER_01_GT
		,LATCH_ANIM_DIE_GT
		,LATCH_ANIM_DIE_NEWRIG
		,LATCH_ANIM_DODGE_GT
		,LATCH_ANIM_DRAGGED_BWD_GT
		,LATCH_ANIM_DRAGGED_FWD_GT_ANIM
		,LATCH_ANIM_IDLE_01_GT
		,LATCH_ANIM_IDLE_NERVOUS_01_GT
		,LATCH_ANIM_IDLE_NERVOUS_01_NEWRIG
		,LATCH_ANIM_IDLE_NERVOUS_TURN_01_GT
		,LATCH_ANIM_IDLE_NERVOUS_TURN_01_NEWRIG
		,LATCH_ANIM_ITEM_GET_GT
		,LATCH_ANIM_ITEM_GET_NEWRIG
		,LATCH_ANIM_JUMP_DOWN_01_NEWRIG
		,LATCH_ANIM_JUMP_DOWN_02_GT
		,LATCH_ANIM_JUMP_DOWN_02_NEWRIG
		,LATCH_ANIM_JUMP_LAND_02_GT
		,LATCH_ANIM_JUMP_START_SHORT_GT
		,LATCH_ANIM_JUMP_START_SHORT_NEWRIG
		,LATCH_ANIM_JUMP_UP_02_GT
		,LATCH_ANIM_JUMPATTACK_RISE_GT
		,LATCH_ANIM_LUNCHBOX_BACKFLIP_GT
		,LATCH_ANIM_LUNCHBOX_POSE_01_LOOP_GT
		,LATCH_ANIM_LUNCHBOX_POSE_02_LOOP_GT
		,LATCH_ANIM_PULL_GT
		,LATCH_ANIM_PULL_LEFT_GT
		,LATCH_ANIM_PULL_RIGHT_GT
		,LATCH_ANIM_PUSH_GT
		,LATCH_ANIM_PUTDOWN_GT
		,LATCH_ANIM_PUTDOWN_NEWRIG
		,LATCH_ANIM_REMOTE_HOLD
		,LATCH_ANIM_REMOTE_PUSH_GT
		,LATCH_ANIM_RUN_01_GT
		,LATCH_ANIM_RUN_SWORD_01_GT
		,LATCH_ANIM_SPIN_ATTACK_INTO_GT
		,LATCH_ANIM_SPIN_ATTACK_OUT_GT
		,LATCH_ANIM_SPIN_ATTACK_SPIN_LOOP_GT
		,LATCH_ANIM_SPRINT_01_NEWRIG
		,LATCH_ANIM_STAMP_ATTACK_EDIT_NEWRIG
		,LATCH_ANIM_STAMP_ATTACK_GT
		,LATCH_ANIM_STAMP_ERASE_GT
		,LATCH_ANIM_STAMP_HOLD_GT
		,LATCH_ANIM_STAMP_HOLD_NEWRIG
		,LATCH_ANIM_STAMP_PULLOUT_SHORT_GT
		,LATCH_ANIM_STAMP_PULLOUT_SHORT_GT_EDIT
		,LATCH_ANIM_STAMP_PULLOUT_SHORT_NEWRIG
		,LATCH_ANIM_STEALTH_RUN_GT
		,LATCH_ANIM_SWORDTHROW_AIM_GT
		,LATCH_ANIM_SWORDTHROW_AIM_NEWRIG
		,LATCH_ANIM_SWORDTHROW_INTO_GT
		,LATCH_ANIM_SWORDTHROW_INTO_NEWRIG
		,LATCH_ANIM_SWORDTHROW_THROW_GT
		,LATCH_ANIM_SWORDTHROW_THROW_NEWRIG
		,LATCH_ANIM_TORCH_STRAFE_BACK_01_GT
		,LATCH_ANIM_TORCH_STRAFE_FWD_01_GT
		,LATCH_ANIM_TORCH_STRAFE_LEFT_01_GT
		,LATCH_ANIM_TORCH_STRAFE_RIGHT_01_GT
		,LATCH_ANIM_TRAILER_OUTBOOK_01_ANIM
		,LATCH_CINE_D09_LB_INTRO_SH_01
		,LATCH_CINE_D09_LB_INTRO_SH_02
		,LATCH_CINE_D09_LB_INTRO_SH_03
		,LATCH_CINE_GAUNTLET_EVENT_SHOT_01_GT
		,LATCH_PICKUP_GT
		,LATCH_PICKUP_IDLE_GT
		,LATCH_PICKUP_IDLE_NEWRIG
		,LATCH_PICKUP_NEWRIG
		,LATCH_STEALTH_IDLE_GT
		,LATCH_THROW_NEWRIG
		,LATCH_ANIM_ATTACK_01_BLOCKED_GT_EDIT
		,LATCH_ANIM_ATTACK_01_GT_EDIT
		,LATCH_ANIM_JUMPATTACK_FALL
		,LATCH_ANIM_JUMPATTACK_LAND_GT_EDIT
		,LATCH_ANIM_JUMPATTACK_RISE
		,LATCH_ANIM_LAST
	};
private:
	CPlayer(ID3D11Device* _pDevice, ID3D11DeviceContext* _pContext);
	CPlayer(const CPlayer& _Prototype);
	virtual ~CPlayer() = default;

public:
	virtual HRESULT			Initialize_Prototype() override;
	virtual HRESULT			Initialize(void* _pArg) override;
	virtual void			Priority_Update(_float _fTimeDelta) override;
	virtual void			Update(_float _fTimeDelta) override;
	virtual void			Late_Update(_float _fTimeDelta) override;
	virtual HRESULT			Render() override;

	void On_AnimEnd(COORDINATE _eCoord, _uint iAnimIdx);
	void Move(_vector _vDir,_float _fTimeDelta);
	void Switch_Animation(_uint _iAnimIndex);
	void Set_State(STATE _eState);
private:
	void					Key_Input(_float _fTimeDelta);

private:
	HRESULT					Ready_Components();
	HRESULT					Ready_PartObjects();

private:
	CStateMachine* m_pStateMachine = nullptr;
public:
	static CPlayer*		Create(ID3D11Device* _pDevice, ID3D11DeviceContext* _pContext);
	virtual CGameObject*	Clone(void* _pArg) override;
	virtual void			Free() override;

};
END
